//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poppel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public int Id { get; set; }
        public string Company { get; set; }
        public int UserId { get; set; }
        public int TransactionId { get; set; }
        public int PaymentId { get; set; }
    
        public virtual Payment Payment { get; set; }
        public virtual Transaction Transaction { get; set; }
        public virtual User User { get; set; }
    }
}
